# Generated by Django 2.2.7 on 2019-12-17 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_url', models.URLField(max_length=250)),
                ('scrapping_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MobileProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField()),
                ('product_rating', models.IntegerField(max_length=2)),
                ('product_review', models.URLField(max_length=250)),
                ('product_price', models.FloatField()),
                ('product_url', models.URLField(max_length=250)),
                ('scrapping_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
