# Generated by Django 2.2.7 on 2019-12-25 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('brand_url', models.URLField(max_length=250)),
                ('product_slug', models.SlugField(max_length=250, unique_for_date='scrapping_time')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('scrapping_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MobileProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_url', models.URLField(max_length=250)),
                ('product_description', models.TextField()),
                ('lowprice', models.IntegerField()),
                ('highprice', models.IntegerField()),
                ('offercount', models.IntegerField()),
                ('scrapping_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapper.CatalogMobile')),
            ],
        ),
    ]
