# Generated by Django 2.2.7 on 2019-12-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmobile',
            name='product_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='product_rating',
            field=models.IntegerField(),
        ),
    ]
