# Generated by Django 2.2.7 on 2019-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20191222_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmobile',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000),
            preserve_default=False,
        ),
    ]
