# Generated by Django 2.2.7 on 2019-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_catalogmobile_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmobile',
            name='product_slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='scrapping_time'),
            preserve_default=False,
        ),
    ]
